### ISSUE TITLE
couldn't wrap context-bound function or method (babel 6.* is used)

### ISSUE THREAD

**Issue by pkantsedalov** [alexandrusavin/exectimer#10]
Hi, 

Here I have a problem.
I try to wrap a class method **inside a constructor**, but my code is ES6+, I use async/await etc. I'm trying to wrap a method in that way:

``` js
Tick.wrap(this.method);
```

But then I have a problem - my **this** is `undefined` inside the method.
But even more: when I try

``` js
Tick.wrap(this.method.bind(this));
```

It doesn't wrap it at ll - `console.log(t.timers)` doesn't show me my method as wrapped, but an empty object.

Thanks in advance.

**Comment by alexandrusavin** [comment]
Sorry for the late reply! Holiday season here :)

Does your method accept a callback? Wrapping expects your method to call the first parameter as a callback when it is done.
