### ISSUE TITLE
Get Last Tick duration

### ISSUE THREAD

**Issue by astanciu** [alexandrusavin/exectimer#8]
Any way to get the duration of the last tick? For example, using this in Express, it'd be nice to keep running stats as the module currently does, but also get the last tick's duration to display with each request.

**Comment by alexandrusavin** [comment]
You should be able to use the timers array to extract the latest tick and call getDiff() on it.

```javascript
const allTicks = t.timers['yourTimerName'].ticks;

const lastTickDuration = allTicks[allTicks.length-1].getDiff();

// to get it in ms you do
const ms = lastTickDuration/1e6;
```

I'll try to add a helper for this.

**Comment by alexandrusavin** [comment]
I'll close this as it can be done by reading the last tick of the ticks array.
