### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by pwellner** [alexandrusavin/exectimer#9]
None of the examples on the README work for me.  Error is
```
TypeError: Cannot read property 'duration' of undefined
```
I can avoid this crash by delaying the display of results section e.g. like so:
```JavaScript
setTimeout(function() {
    // Display the results                                                                                                                   
    var myFunc_timer = t.timers.myFunction;
    console.log(myFunc_timer.duration()); // total duration of all ticks                                                                     
    console.log(myFunc_timer.min());      // minimal tick duration                                                                           
    console.log(myFunc_timer.max());      // maximal tick duration                                                                           
    console.log(myFunc_timer.mean());     // mean tick duration                                                                              
    console.log(myFunc_timer.median());   // median tick duration                                                                            
    },
    1000
);
```

If that were the only problem this module would still be useable, but there's another problem.  The min/max/mean are always all identical, even when I include a random timeout in the loop something like this:
```JavaScript
for(var i = 0; i < 10; i++) {
  var tick = new Tick("myFunction");
  tick.start();

  setTimeout(function() {
    tick.stop();
  }, Math.random() * 100);
}
```

I see the same issue with several vesions of node, including 4.0.0 listed as the "engines" property of the `package.json`

There's no test for when min/max/median etc can be different from each other, so all 39 tests are passing.

**Comment by alexandrusavin** [comment]
Thanks for opening this issue and for the detailed info. I'll fix it asap

**Comment by alexandrusavin** [comment]
Related to the second issue (same median, mean etc) you posted, the problem is that the example that I gave in the Readme is very bad. 

The contexts are mixing and the tick.stop is basically executed on the same last tick because when setTimeout kicks in all the loops are done already. So it's an aliasing issue.

To solve this issue you should create a separate context for each loop:
```javascript
for(var i = 0; i < 10; i++) {
    (function () {
        var tick = new Tick("myFunction");
        tick.start();

        setTimeout(function() {
            tick.stop();
        }, Math.random() * 100);
    })();
}
```

**Comment by alexandrusavin** [comment]
Related to the first issue, you're probably trying to execute the helpers before any of the ticks called stop() method.

Can you please give me a full example that reproduces this issue?

Thanks!

**Comment by pwellner** [comment]
I had simply copied and pasted each of the 3 README examples (before your most recent change).

**Comment by alexandrusavin** [comment]
Latest commit (e2ec6d4) should fix it
